services:
  turtle-backend:
    build:
      target: development
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend_network
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres-db:
        condition: service_healthy
    develop:
      watch:
        # Sincronizacion para cualquier codigo de src. Ignoramos el codigo cliente generado de prisma ya que este
        # es propio por sistema operativo. Ademas que se obtiene por medio de observaciones en ./prisma
        - path: ./src
          action: sync
          target: /usr/src/app/src
          ignore:
            - src/generated/
        # Sincronizacion y reinicio del contenedor cada vez que se actualiza el schema de prisma por una migracion
        # Esto para que el contenedor tenga todas las migraciones a su alcance y tambien el codigo mas actualizado
        # del Prisma Client.
        - path: ./prisma
          action: sync+restart
          target: /usr/src/app/prisma
        # recostruccion total del contenedor cuando se agrega y/o eliminan dependencias
        - action: rebuild
          path: package.json
  postgres-db:
    image: postgres:18-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DATABASE_NAME}", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_USER: ${DATABASE_DEFAULT_SUPERUSER}
      POSTGRES_PASSWORD: ${DATABASE_SUPERUSER_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGUSER: ${DATABASE_DEFAULT_SUPERUSER}
      PGPASSWORD: ${DATABASE_SUPERUSER_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/18/docker
      - ./database/scripts/initialization:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
    networks:
      - backend_network
      - dba_network
  pgadmin:
    image: dpage/pgadmin4:9.14.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    profiles:
      - dbClient
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${HOST_PGADMIN_PORT}:80
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m
    networks:
      - dba_network