services:
  turtle-backend:
    build:
      context: .
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
volumes:
  pg-data:
  pg-admin-data:
networks:
  backend_network:
    driver: "bridge"
  dba_network:
    driver: "bridge"
