services:
  turtle-backend:
    restart: always
    build:
      target: production
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend_network
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production