services:
  turtle-backend:
    restart: always
    build:
      target: production
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend_network
    environment:
      PORT: ${PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      NODE_ENV: production