-- Corrige la migracion 20260917221458 que anadio por error GENERATED BY DEFAULT AS IDENTITY
-- a "Cliente_Digital"."id". Esta columna es PK+FK hacia "Usuario"(id) y no debe autoincrementar.
ALTER TABLE "Cliente_Digital" ALTER COLUMN "id" DROP IDENTITY IF EXISTS;
